service: slackbot-calendar
frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: python3.9.5
  region: ap-northwest-2
  profile: hsh108868
  environment:
    SLACK_BOT_TOKEN: ${ssm:/slackbot-calendar/slack-bot-token}
    SLACK_SIGNING_SECRET: ${ssm:/slackbot-calendar/slack-signing-secret}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObeject"
          Resource: "arn:aws:s3:::slackbot-calendar/*"

resources:
  Resources:
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: slackbot-calendar

functions:
  slack:
    handler: src/index.handler
    url: cors:true
